# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UvX9IlxwPtCt96lG7s8tLksuK5dL3K0h
"""

x=int(input("x = "))
y=int(input("y = "))
diff = x
while y> 0:
  diff -= 1
  y -= 1

print(f"x - y = {diff}")

x=int(input("x = "))
y=int(input("y = "))
remainder = x
quotient = 0
while remainder>y:
 remainder -= y
 quotient +=1
print(f"x div y = {quotient}")
print(f"x mod y = {remainder}")

