# -*- coding: utf-8 -*-
"""anime.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWqdX8lRdF6ZqBuEFI_Dwt-UBJ5xgnLF
"""

import time
from IPython.display import clear_output


base = 1000000000000000000000000000

imgs = [
        1000000000000000000000000000,
        1000000000000000000000000000,
        1000000000110000110000000000,
        1000000000110000110000000000,
        1000000000000000000000000000,
        1000001100000000000011000000,
        1000000110000000000110000000,
        1000000011000000001100000000,
        1000000000111111110000000000,
        1000000000000000000000000000
       ]

t = 1
while t < 13:
  clear_output(wait=True)
  for line in imgs:
    print(line)     
  print()    
  
  if t%4== 1:
    for i in range(len(imgs)):
      if i<len(imgs)-1:
        imgs[i] = ((imgs[i+1]%base)//10)+base  
    
  if t%4== 2:
    for i in range(len(imgs)):
       if i<len(imgs)-1:
         imgs[i] = ((imgs[i+1]%base)*10)+base
    
  if t%4== 3:
    for i in range(len(imgs)):
      if i>1:
        imgs[len(imgs)-i]=((imgs[len(imgs)-i-1]%base)*10)+base
    imgs[0]=imgs[len(imgs)-1]  
  if t%4==0:
    for i in range(len(imgs)):
      if i>1:
        imgs[len(imgs)-i]=((imgs[len(imgs)-i-1]%base)//10)+base
    imgs[0]=imgs[len(imgs)-1]

  time.sleep(0.5)
  t+=1

k=1
while k<50:
  clear_output(wait=True)
  for line in imgs:
    print(line)    
  print() 
  if k<= len(imgs):
    for i in range(k):
      if imgs[len(imgs)-i-1]!= "":
        imgs[len(imgs)-i-1] = imgs[len(imgs)-i-1] //10
      if imgs[len(imgs)-i-1] == 0:
        imgs[len(imgs)-i-1] = ""
      
  if k> len(imgs):
    for i in range(len(imgs)):
      if imgs[len(imgs)-i-1]!= "":
        imgs[len(imgs)-i-1] = imgs[len(imgs)-i-1] //10
      if imgs[len(imgs)-i-1] == 0:
        imgs[len(imgs)-i-1] = ""
      

  time.sleep(0.2)
  k+=1

