# -*- coding: utf-8 -*-
"""hw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MiqomzEHFp0mBJbKrRaIRJoCB_aZhbG9
"""

numbers = list(map(int, input("Write some numbers: ").split()))
max_value= -100000          # to represent minus infinity
max_index= -1
num1 = numbers[0]
num2 = 0
for k in range(len(numbers)-1): # You can change this line
  
  if numbers[k+1]>=num1:
    num1 = numbers[k+1]
    num2=k+1

  max_value = num1
  max_index = num2

print("max_value = ", max_value)
print("max_index = ", max_index)

s = input("Input a string: ")

a = list(s.encode("ascii")) # You may remove this line
for i in range(len(a)):     # You can change this line
  if a[i] in range(97,123):
    print (chr(a[i]))

